services:
  vunov:
    image: vunov:0.1
    container_name: vunov
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sleep", "infinity"]
    privileged: true
    volumes:
      - ../ai/.pi:/home/ubuntu/.pi
      - ../ai/.engram:/home/ubuntu/.engram
      - ../ai/.opencode:/home/ubuntu/.opencode   # sesión persistente
    env_file:
      - ../.env